/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ResourceLog = IDL.Record({
  'selected_policy' : IDL.Text,
  'active_processes' : IDL.Nat,
  'cpu_usage' : IDL.Float64,
  'io_bandwidth' : IDL.Float64,
  'log_id' : IDL.Nat,
  'decision_confidence' : IDL.Float64,
  'timestamp' : Timestamp,
  'memory_usage' : IDL.Float64,
});
export const PaginatedLogs = IDL.Record({
  'page_size' : IDL.Nat,
  'total' : IDL.Nat,
  'logs' : IDL.Vec(ResourceLog),
  'page' : IDL.Nat,
});
export const MetricsSnapshot = IDL.Record({
  'active_processes' : IDL.Nat,
  'cpu_usage' : IDL.Float64,
  'io_bandwidth' : IDL.Float64,
  'timestamp' : Timestamp,
  'memory_usage' : IDL.Float64,
});
export const ProcessId = IDL.Text;
export const Process = IDL.Record({
  'pid' : ProcessId,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'burst_time' : IDL.Float64,
  'priority' : IDL.Nat,
  'arrival_time' : Timestamp,
});
export const AggregatedStats = IDL.Record({
  'total_completed' : IDL.Nat,
  'throughput_tasks_per_sec' : IDL.Float64,
  'avg_turnaround_time' : IDL.Float64,
  'avg_waiting_time' : IDL.Float64,
});
export const SchedulingDecision = IDL.Record({
  'reasoning' : IDL.Text,
  'confidence' : IDL.Float64,
  'override_active' : IDL.Bool,
  'features_used' : IDL.Vec(IDL.Text),
  'policy' : IDL.Text,
});
export const SubmitProcessReceipt = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
  'process_id' : ProcessId,
});

export const idlService = IDL.Service({
  'clearData' : IDL.Func([], [], []),
  'getLogs' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedLogs], ['query']),
  'getMetrics' : IDL.Func([], [MetricsSnapshot], ['query']),
  'getProcesses' : IDL.Func([], [IDL.Vec(Process)], ['query']),
  'getResults' : IDL.Func([], [AggregatedStats], ['query']),
  'getSchedulingDecision' : IDL.Func([], [SchedulingDecision], ['query']),
  'overridePolicy' : IDL.Func([IDL.Text], [], []),
  'startSimulation' : IDL.Func([IDL.Nat], [], []),
  'submitMetrics' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'submitProcess' : IDL.Func(
      [ProcessId, IDL.Text, IDL.Nat, IDL.Float64, Timestamp],
      [SubmitProcessReceipt],
      [],
    ),
  'submitSchedulingResult' : IDL.Func(
      [ProcessId, IDL.Float64, IDL.Float64, Timestamp, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ResourceLog = IDL.Record({
    'selected_policy' : IDL.Text,
    'active_processes' : IDL.Nat,
    'cpu_usage' : IDL.Float64,
    'io_bandwidth' : IDL.Float64,
    'log_id' : IDL.Nat,
    'decision_confidence' : IDL.Float64,
    'timestamp' : Timestamp,
    'memory_usage' : IDL.Float64,
  });
  const PaginatedLogs = IDL.Record({
    'page_size' : IDL.Nat,
    'total' : IDL.Nat,
    'logs' : IDL.Vec(ResourceLog),
    'page' : IDL.Nat,
  });
  const MetricsSnapshot = IDL.Record({
    'active_processes' : IDL.Nat,
    'cpu_usage' : IDL.Float64,
    'io_bandwidth' : IDL.Float64,
    'timestamp' : Timestamp,
    'memory_usage' : IDL.Float64,
  });
  const ProcessId = IDL.Text;
  const Process = IDL.Record({
    'pid' : ProcessId,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'burst_time' : IDL.Float64,
    'priority' : IDL.Nat,
    'arrival_time' : Timestamp,
  });
  const AggregatedStats = IDL.Record({
    'total_completed' : IDL.Nat,
    'throughput_tasks_per_sec' : IDL.Float64,
    'avg_turnaround_time' : IDL.Float64,
    'avg_waiting_time' : IDL.Float64,
  });
  const SchedulingDecision = IDL.Record({
    'reasoning' : IDL.Text,
    'confidence' : IDL.Float64,
    'override_active' : IDL.Bool,
    'features_used' : IDL.Vec(IDL.Text),
    'policy' : IDL.Text,
  });
  const SubmitProcessReceipt = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
    'process_id' : ProcessId,
  });
  
  return IDL.Service({
    'clearData' : IDL.Func([], [], []),
    'getLogs' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedLogs], ['query']),
    'getMetrics' : IDL.Func([], [MetricsSnapshot], ['query']),
    'getProcesses' : IDL.Func([], [IDL.Vec(Process)], ['query']),
    'getResults' : IDL.Func([], [AggregatedStats], ['query']),
    'getSchedulingDecision' : IDL.Func([], [SchedulingDecision], ['query']),
    'overridePolicy' : IDL.Func([IDL.Text], [], []),
    'startSimulation' : IDL.Func([IDL.Nat], [], []),
    'submitMetrics' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'submitProcess' : IDL.Func(
        [ProcessId, IDL.Text, IDL.Nat, IDL.Float64, Timestamp],
        [SubmitProcessReceipt],
        [],
      ),
    'submitSchedulingResult' : IDL.Func(
        [ProcessId, IDL.Float64, IDL.Float64, Timestamp, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };