/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AggregatedStats {
  'total_completed' : bigint,
  'throughput_tasks_per_sec' : number,
  'avg_turnaround_time' : number,
  'avg_waiting_time' : number,
}
export interface MetricsSnapshot {
  'active_processes' : bigint,
  'cpu_usage' : number,
  'io_bandwidth' : number,
  'timestamp' : Timestamp,
  'memory_usage' : number,
}
export interface PaginatedLogs {
  'page_size' : bigint,
  'total' : bigint,
  'logs' : Array<ResourceLog>,
  'page' : bigint,
}
export interface Process {
  'pid' : ProcessId,
  'status' : string,
  'name' : string,
  'burst_time' : number,
  'priority' : bigint,
  'arrival_time' : Timestamp,
}
export type ProcessId = string;
export interface ResourceLog {
  'selected_policy' : string,
  'active_processes' : bigint,
  'cpu_usage' : number,
  'io_bandwidth' : number,
  'log_id' : bigint,
  'decision_confidence' : number,
  'timestamp' : Timestamp,
  'memory_usage' : number,
}
export interface SchedulingDecision {
  'reasoning' : string,
  'confidence' : number,
  'override_active' : boolean,
  'features_used' : Array<string>,
  'policy' : string,
}
export interface SubmitProcessReceipt {
  'message' : string,
  'success' : boolean,
  'process_id' : ProcessId,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'clearData' : ActorMethod<[], undefined>,
  'getLogs' : ActorMethod<[bigint, bigint], PaginatedLogs>,
  'getMetrics' : ActorMethod<[], MetricsSnapshot>,
  'getProcesses' : ActorMethod<[], Array<Process>>,
  'getResults' : ActorMethod<[], AggregatedStats>,
  'getSchedulingDecision' : ActorMethod<[], SchedulingDecision>,
  'overridePolicy' : ActorMethod<[string], undefined>,
  'startSimulation' : ActorMethod<[bigint], undefined>,
  'submitMetrics' : ActorMethod<[number, number, bigint, number], undefined>,
  'submitProcess' : ActorMethod<
    [ProcessId, string, bigint, number, Timestamp],
    SubmitProcessReceipt
  >,
  'submitSchedulingResult' : ActorMethod<
    [ProcessId, number, number, Timestamp, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];