/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ProcessId = string;
export interface PaginatedLogs {
    page_size: bigint;
    total: bigint;
    logs: Array<ResourceLog>;
    page: bigint;
}
export type Timestamp = bigint;
export interface MetricsSnapshot {
    active_processes: bigint;
    cpu_usage: number;
    io_bandwidth: number;
    timestamp: Timestamp;
    memory_usage: number;
}
export interface ResourceLog {
    selected_policy: string;
    active_processes: bigint;
    cpu_usage: number;
    io_bandwidth: number;
    log_id: bigint;
    decision_confidence: number;
    timestamp: Timestamp;
    memory_usage: number;
}
export interface AggregatedStats {
    total_completed: bigint;
    throughput_tasks_per_sec: number;
    avg_turnaround_time: number;
    avg_waiting_time: number;
}
export interface SubmitProcessReceipt {
    message: string;
    success: boolean;
    process_id: ProcessId;
}
export interface Process {
    pid: ProcessId;
    status: string;
    name: string;
    burst_time: number;
    priority: bigint;
    arrival_time: Timestamp;
}
export interface SchedulingDecision {
    reasoning: string;
    confidence: number;
    override_active: boolean;
    features_used: Array<string>;
    policy: string;
}
export interface backendInterface {
    clearData(): Promise<void>;
    getLogs(page: bigint, page_size: bigint): Promise<PaginatedLogs>;
    getMetrics(): Promise<MetricsSnapshot>;
    getProcesses(): Promise<Array<Process>>;
    getResults(): Promise<AggregatedStats>;
    getSchedulingDecision(): Promise<SchedulingDecision>;
    overridePolicy(policy: string): Promise<void>;
    startSimulation(processCount: bigint): Promise<void>;
    submitMetrics(cpu: number, memory: number, active_processes: bigint, io_bandwidth: number): Promise<void>;
    submitProcess(pid: ProcessId, name: string, priority: bigint, burst_time: number, arrival_time: Timestamp): Promise<SubmitProcessReceipt>;
    submitSchedulingResult(pid: ProcessId, waiting_time: number, turnaround_time: number, completion_time: Timestamp, policy_applied: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearData();
            return result;
        }
    }
    async getLogs(arg0: bigint, arg1: bigint): Promise<PaginatedLogs> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogs(arg0, arg1);
            return result;
        }
    }
    async getMetrics(): Promise<MetricsSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return result;
        }
    }
    async getProcesses(): Promise<Array<Process>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProcesses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProcesses();
            return result;
        }
    }
    async getResults(): Promise<AggregatedStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResults();
            return result;
        }
    }
    async getSchedulingDecision(): Promise<SchedulingDecision> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchedulingDecision();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchedulingDecision();
            return result;
        }
    }
    async overridePolicy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.overridePolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.overridePolicy(arg0);
            return result;
        }
    }
    async startSimulation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSimulation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSimulation(arg0);
            return result;
        }
    }
    async submitMetrics(arg0: number, arg1: number, arg2: bigint, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMetrics(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMetrics(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitProcess(arg0: ProcessId, arg1: string, arg2: bigint, arg3: number, arg4: Timestamp): Promise<SubmitProcessReceipt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProcess(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProcess(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitSchedulingResult(arg0: ProcessId, arg1: number, arg2: number, arg3: Timestamp, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSchedulingResult(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSchedulingResult(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
